import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
export const DEFAULT_SCHEMA = path.resolve(SCRIPT_DIR, '../../openapi/openapi.json')
export const DEFAULT_OUTPUT = path.resolve(SCRIPT_DIR, '../src/types/api-generated.ts')
export const HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`

export async function renderApiTypes(schemaPath = DEFAULT_SCHEMA) {
  const schemaText = await fs.readFile(schemaPath, 'utf8')
  const schema = JSON.parse(schemaText)
  const body = astToString(await openapiTS(schema))
  return `${HEADER}${body.replaceAll('\r\n', '\n').replace(/\n*$/, '\n')}`
}

export async function writeApiTypes(schemaPath = DEFAULT_SCHEMA, outputPath = DEFAULT_OUTPUT) {
  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, await renderApiTypes(schemaPath), 'utf8')
}

export async function checkApiTypes(schemaPath = DEFAULT_SCHEMA, outputPath = DEFAULT_OUTPUT) {
  const expected = await renderApiTypes(schemaPath)
  let actual = ''
  try {
    actual = await fs.readFile(outputPath, 'utf8')
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error
  }
  if (actual === expected) return true
  console.error('Generated API type drift detected.')
  console.error(`Expected: ${outputPath}`)
  console.error('Fix: npm run generate:api')
  return false
}

export async function main(argv = process.argv.slice(2)) {
  const [command = 'check', schemaPath = DEFAULT_SCHEMA, outputPath = DEFAULT_OUTPUT] = argv
  if (command === 'write') {
    await writeApiTypes(schemaPath, outputPath)
    return 0
  }
  if (command === 'check') return (await checkApiTypes(schemaPath, outputPath)) ? 0 : 1
  console.error('Usage: node scripts/openapi-codegen.mjs <write|check> [schema] [output]')
  return 2
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  process.exitCode = await main()
}
