"""Create the isolated per-space database schema.

Revision ID: space_001
Revises:
Create Date: 2026-07-02 05:47:45.886392

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "space_001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('trashed_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folder_parent_name')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_trashed_at'), ['trashed_at'], unique=False)
        batch_op.create_index('uq_folder_root_name', ['name'], unique=True, sqlite_where=sa.text('parent_id IS NULL'))

    op.create_table('habit_check_ins',
    sa.Column('habit_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=10000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_check_ins'))
    )
    with op.batch_alter_table('habit_check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_check_ins_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_check_ins_habit_id'), ['habit_id'], unique=False)

    op.create_table('habits',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('rest_day_protection', sa.Boolean(), nullable=False),
    sa.Column('rest_days', sa.String(length=4000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits'))
    )
    op.create_table('memo_comments',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memo_comments'))
    )
    with op.batch_alter_table('memo_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memo_comments_note_id'), ['note_id'], unique=False)

    op.create_table('notes',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.String(length=4000), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trashed_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_trashed_at'), ['trashed_at'], unique=False)

    op.create_table('quick_notes',
    sa.Column('content', sa.String(length=50000), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=4000), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.String(length=32), nullable=True),
    sa.Column('archive_file_path', sa.String(length=500), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('trashed_at', sa.String(length=32), nullable=True),
    sa.Column('migrated_to_note_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("mood IN ('normal','happy','sad','tired','excited','calm') OR mood IS NULL", name=op.f('ck_quick_notes_check_quick_note_mood')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_notes'))
    )
    with op.batch_alter_table('quick_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_notes_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_notes_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_notes_migrated_to_note_id'), ['migrated_to_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_notes_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_notes_trashed_at'), ['trashed_at'], unique=False)

    op.create_table('reflections',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=50000), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('related_task_ids', sa.String(length=4000), nullable=False),
    sa.Column('tags', sa.String(length=4000), nullable=False),
    sa.Column('sections', sa.String(length=4000), nullable=False),
    sa.Column('is_structured', sa.Boolean(), nullable=False),
    sa.Column('auto_linked_session_ids', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("mood IN ('great','good','normal','bad','terrible')", name=op.f('ck_reflections_check_reflection_mood')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reflections'))
    )
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.create_index('idx_reflection_date_mood', ['date', 'mood'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflections_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reflections_mood'), ['mood'], unique=False)

    op.create_table('schedule_quick_notes',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('quick_note_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_quick_notes'))
    )
    with op.batch_alter_table('schedule_quick_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_quick_notes_quick_note_id'), ['quick_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_quick_notes_schedule_id'), ['schedule_id'], unique=False)

    op.create_table('schedules',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('due_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('high','medium','low')", name=op.f('ck_schedules_check_schedule_priority')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_table('session_quick_notes',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('quick_note_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_quick_notes'))
    )
    with op.batch_alter_table('session_quick_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_quick_notes_quick_note_id'), ['quick_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_quick_notes_session_id'), ['session_id'], unique=False)

    op.create_table('sessions',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=10000), nullable=False),
    sa.Column('completion', sa.String(length=10000), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('ended_at', sa.String(length=32), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=10000), nullable=False),
    sa.Column('attention_score', sa.Integer(), nullable=True),
    sa.Column('flow_state_detected', sa.Boolean(), nullable=True),
    sa.Column('flow_state_confidence', sa.Float(), nullable=True),
    sa.Column('interruption_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_interruption_duration', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_recovery_time', sa.Integer(), nullable=True),
    sa.Column('pause_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_pause_duration', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('cognitive_mark_summary', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('work','short_break','long_break','free','countdown')", name=op.f('ck_sessions_check_session_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('sync_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_audit_log'))
    )
    op.create_table('sync_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('synced_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_outbox'))
    )
    op.create_table('task_quick_notes',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('quick_note_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_quick_notes'))
    )
    with op.batch_alter_table('task_quick_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_quick_notes_quick_note_id'), ['quick_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_quick_notes_task_id'), ['task_id'], unique=False)

    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=4000), nullable=False),
    sa.Column('plan', sa.String(length=10000), nullable=False),
    sa.Column('completion', sa.String(length=10000), nullable=False),
    sa.Column('due_date', sa.String(length=32), nullable=True),
    sa.Column('estimated_pomodoros', sa.Integer(), nullable=False),
    sa.Column('actual_pomodoros', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','urgent')", name=op.f('ck_tasks_check_task_priority')),
    sa.CheckConstraint("status IN ('todo','in_progress','done','archived')", name=op.f('ck_tasks_check_task_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('time_blocks',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('planned_duration', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("block_type IN ('work','short_break','long_break')", name=op.f('ck_time_blocks_check_timeblock_type')),
    sa.CheckConstraint("status IN ('planned','in_progress','completed','skipped')", name=op.f('ck_time_blocks_check_timeblock_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_blocks'))
    )
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_blocks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_blocks_task_id'), ['task_id'], unique=False)

    op.create_table('tombstones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tombstones')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_tombstone_entity')
    )
    with op.batch_alter_table('tombstones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tombstones_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tombstones_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tombstones_entity_type'), ['entity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tombstones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tombstones_entity_type'))
        batch_op.drop_index(batch_op.f('ix_tombstones_entity_id'))
        batch_op.drop_index(batch_op.f('ix_tombstones_deleted_at'))

    op.drop_table('tombstones')
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_blocks_task_id'))
        batch_op.drop_index(batch_op.f('ix_time_blocks_date'))

    op.drop_table('time_blocks')
    op.drop_table('tasks')
    with op.batch_alter_table('task_quick_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_quick_notes_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_quick_notes_quick_note_id'))

    op.drop_table('task_quick_notes')
    op.drop_table('sync_outbox')
    op.drop_table('sync_audit_log')
    op.drop_table('settings')
    op.drop_table('sessions')
    with op.batch_alter_table('session_quick_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_quick_notes_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_quick_notes_quick_note_id'))

    op.drop_table('session_quick_notes')
    op.drop_table('schedules')
    with op.batch_alter_table('schedule_quick_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_quick_notes_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_quick_notes_quick_note_id'))

    op.drop_table('schedule_quick_notes')
    with op.batch_alter_table('reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflections_mood'))
        batch_op.drop_index(batch_op.f('ix_reflections_date'))
        batch_op.drop_index('idx_reflection_date_mood')

    op.drop_table('reflections')
    with op.batch_alter_table('quick_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_notes_trashed_at'))
        batch_op.drop_index(batch_op.f('ix_quick_notes_session_id'))
        batch_op.drop_index(batch_op.f('ix_quick_notes_migrated_to_note_id'))
        batch_op.drop_index(batch_op.f('ix_quick_notes_folder_id'))
        batch_op.drop_index(batch_op.f('ix_quick_notes_archived_at'))

    op.drop_table('quick_notes')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_trashed_at'))
        batch_op.drop_index(batch_op.f('ix_notes_status'))
        batch_op.drop_index(batch_op.f('ix_notes_folder_id'))
        batch_op.drop_index(batch_op.f('ix_notes_category'))

    op.drop_table('notes')
    with op.batch_alter_table('memo_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memo_comments_note_id'))

    op.drop_table('memo_comments')
    op.drop_table('habits')
    with op.batch_alter_table('habit_check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_check_ins_habit_id'))
        batch_op.drop_index(batch_op.f('ix_habit_check_ins_date'))

    op.drop_table('habit_check_ins')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('uq_folder_root_name', sqlite_where=sa.text('parent_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_folders_trashed_at'))
        batch_op.drop_index(batch_op.f('ix_folders_parent_id'))

    op.drop_table('folders')
    # ### end Alembic commands ###
